name: PR Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            auth
            api
            ui
            db
            infra
            billing
